# Site settings
title: ARMstrap
email: your-email@domain.com
description: ARMing the Next-Generation Engineer
baseurl: ""
url: "http://armstrap.org"
twitter_username: armstrap
github_username:  armstrap

# Build settings
markdown: kramdown
