
#
# Site settings
#
author: Charles Armstrap
url: http://armstrap.org
title: Armstrap
email: your-email@domain.com
tagline: Arming the Next-Generation Engineer
baseurl: ""
description: Armstrap is a community of engineers and makers determined to help make ARM prototyping easy and fun.

collections:
  products:
    output: true

#
# Social Media
#
social:
  - title: twitter
    url: https://twitter.com/armstrap
  - title: github
    url: https://github.com/armstrap
  - title: rss
    url: /feed.xml

#
# Google Analytics
# 
google_analytics_tracking_id: UA-44329536-1


#
# Disqus Comments
#
disqus_short_name: armstrap-org
disqus_show_comment_count: true


#
# Jekyll Settings
#
markdown: kramdown
permalink: pretty


#
# Jekyll Plugins (Compatible with Github Pages)
#
gems:
 - jekyll-mentions
 - jemoji
 - jekyll-redirect-from
 - jekyll-sitemap

 
