
#
# Site settings
#
author: Charles Armstrap
url: "http://armstrap.org"
title: ARMstrap
tagline: ARMing the Next-Generation Engineer
baseurl: ""
description: >
  ARMstrap is a community of engineers and makers 
  determined to help make ARM prototyping easy and fun.


#
# Social Media
#
twitter_username: armstrap
github_username:  armstrap
youtube_username: armstrap


#
# Google Analytics
# 
google_analytics_tracking_id: UA-44329536-1


#
# Disqus Comments
#
disqus_short_name: armstrap-org
disqus_show_comment_count: true


#
# Jekyll Settings
#
markdown: kramdown


#
# Jekyll Plugins (Compatible with Github Pages)
#
gems:
 - jekyll-mentions
 - jemoji
 - jekyll-redirect-from
 - jekyll-sitemap

